# fly.toml file generated for yjs-demo on 2023-08-21T21:42:34-04:00

app = "yjs-demo"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"
processes = []


[env]
PORT = "12345"

[[statics]]
guest_path = "/app/browser/dist"
url_prefix = "/"

[[services]]
internal_port = 12345
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
